# reference: https://starship.rs/zh-CN/config
# è®¾ç½®é…ç½®èŒƒä¾‹ï¼Œå¼€å¯ç¼–è¾‘å™¨çš„è‡ªåŠ¨è¡¥å…¨
"$schema" = 'https://starship.rs/config-schema.json'

# åœ¨å‘½ä»¤ä¹‹é—´æ’å…¥ç©ºè¡Œ
add_newline = true

[hostname]
ssh_only = false
format = "[@$hostname]($style) in "

# User module
[username]
format = "[$user]($style)"
# show_always = true

[container]
symbol = "ğŸ“¦"
format = "[$symbol]($style) "
